version: 0.2

phases:
  install:
    commands:
      - echo "Install phase - no additional installation needed"
  pre_build:
    commands:
      - echo "Pre-build phase"
  build:
    commands:
      - echo "Starting Maven build"
      - mvn -B clean package
  post_build:
    commands:
      - echo "Build completed, preparing artifacts"

artifacts:
  files:
    - target/demo-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - scripts/*
